# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Wed Jun 12 17:33:38 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(35, 20, 700, 300))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.curve = QtWidgets.QWidget(self.groupBox)
        self.curve.setGeometry(QtCore.QRect(0, 50, 700, 250))
        self.curve.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(114, 159, 207);")
        self.curve.setObjectName("curve")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(660, 30, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(35, 340, 325, 275))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.setWind = QtWidgets.QSpinBox(self.groupBox_2)
        self.setWind.setGeometry(QtCore.QRect(170, 170, 121, 40))
        self.setWind.setMaximum(10)
        self.setWind.setProperty("value", 10)
        self.setWind.setObjectName("setWind")
        self.setTemp = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.setTemp.setGeometry(QtCore.QRect(170, 70, 121, 40))
        self.setTemp.setDecimals(2)
        self.setTemp.setSingleStep(0.1)
        self.setTemp.setProperty("value", 26.0)
        self.setTemp.setObjectName("setTemp")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 340, 325, 275))
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_1.setEnabled(True)
        self.checkBox_1.setGeometry(QtCore.QRect(30, 60, 80, 30))
        self.checkBox_1.setCheckable(True)
        self.checkBox_1.setChecked(False)
        self.checkBox_1.setAutoRepeat(False)
        self.checkBox_1.setAutoExclusive(False)
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 90, 80, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 120, 80, 30))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 150, 80, 30))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setEnabled(True)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 180, 80, 30))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setEnabled(True)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 210, 80, 30))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(120, 90, 80, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(120, 170, 80, 25))
        self.label_2.setObjectName("label_2")
        self.power = QtWidgets.QLabel(self.groupBox_3)
        self.power.setGeometry(QtCore.QRect(200, 90, 80, 25))
        self.power.setText("")
        self.power.setObjectName("power")
        self.gear = QtWidgets.QLabel(self.groupBox_3)
        self.gear.setGeometry(QtCore.QRect(200, 170, 80, 25))
        self.gear.setText("")
        self.gear.setObjectName("gear")
        self.tempLabel_1 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_1.setGeometry(QtCore.QRect(0, 60, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_1.setFont(font)
        self.tempLabel_1.setText("")
        self.tempLabel_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_1.setObjectName("tempLabel_1")
        self.tempLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_2.setGeometry(QtCore.QRect(0, 85, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_2.setFont(font)
        self.tempLabel_2.setText("")
        self.tempLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_2.setObjectName("tempLabel_2")
        self.tempLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_3.setGeometry(QtCore.QRect(0, 110, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_3.setFont(font)
        self.tempLabel_3.setText("")
        self.tempLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_3.setObjectName("tempLabel_3")
        self.tempLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_4.setGeometry(QtCore.QRect(0, 135, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_4.setFont(font)
        self.tempLabel_4.setText("")
        self.tempLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_4.setObjectName("tempLabel_4")
        self.tempLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_5.setGeometry(QtCore.QRect(0, 160, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_5.setFont(font)
        self.tempLabel_5.setText("")
        self.tempLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_5.setObjectName("tempLabel_5")
        self.tempLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_6.setGeometry(QtCore.QRect(0, 185, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_6.setFont(font)
        self.tempLabel_6.setText("")
        self.tempLabel_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_6.setObjectName("tempLabel_6")
        self.tempLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_7.setGeometry(QtCore.QRect(0, 210, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_7.setFont(font)
        self.tempLabel_7.setText("")
        self.tempLabel_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_7.setObjectName("tempLabel_7")
        self.tempLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_8.setGeometry(QtCore.QRect(0, 235, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_8.setFont(font)
        self.tempLabel_8.setText("")
        self.tempLabel_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_8.setObjectName("tempLabel_8")
        self.tempLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_9.setGeometry(QtCore.QRect(0, 260, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_9.setFont(font)
        self.tempLabel_9.setText("")
        self.tempLabel_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_9.setObjectName("tempLabel_9")
        self.tempLabel_10 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_10.setGeometry(QtCore.QRect(0, 285, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_10.setFont(font)
        self.tempLabel_10.setText("")
        self.tempLabel_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_10.setObjectName("tempLabel_10")
        self.tempLabel_11 = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel_11.setGeometry(QtCore.QRect(0, 310, 35, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tempLabel_11.setFont(font)
        self.tempLabel_11.setText("")
        self.tempLabel_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel_11.setObjectName("tempLabel_11")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.setTemp, self.setWind)
        MainWindow.setTabOrder(self.setWind, self.checkBox_1)
        MainWindow.setTabOrder(self.checkBox_1, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.checkBox_4)
        MainWindow.setTabOrder(self.checkBox_4, self.checkBox_5)
        MainWindow.setTabOrder(self.checkBox_5, self.checkBox_6)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "温度曲线", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "温度T", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "℃", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "用户设定", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "预设温度:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "预设风量:", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "系统状态", None, -1))
        self.checkBox_1.setText(QtWidgets.QApplication.translate("MainWindow", "  门1", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "  门2", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "  窗1", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("MainWindow", "  窗2", None, -1))
        self.checkBox_5.setText(QtWidgets.QApplication.translate("MainWindow", "  窗3", None, -1))
        self.checkBox_6.setText(QtWidgets.QApplication.translate("MainWindow", "  窗4", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "加热功率", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "风机档位", None, -1))

