#include<stdio.h>
void cal(long long a,int num);
int main()
{
	int no=0;
	unsigned long long a;
	while (scanf("%llu",&a)!=EOF)
	{
		if (no) printf("\n\n");
		else no++; 	
		printf("Hailstone generated by %llu:\n",a);
	    cal(a,1);
	}
	return 0;
}
void cal(long long a,int num)
{
	if (a==1) {
	   printf("1\nNumber of hailstone generated:%d",num);
	   return ; 
	} 
	else {
		printf("%llu ",a);
		if (a%2==1) cal(3*a+1,num+1);
		else cal(a/2,num+1);
	}
}
