#include<stdio.h>
#include<string.h>
int a[108];
char c[108];
void init(int *a,char *c);
void ditui(int *a);
void cal(int *a,int num);
void print(int *a);
int main()
{
	int no=0;
	while (scanf("%s",c)!=EOF)
	{
		if (no) printf("\n\n");
		else no++;
	    init(a,c);
	    printf("Hailstone generated by ");
		print(a);
		printf(":\n");
	    cal(a,1);
	}	
	return 0;
} 
void init(int *a,char *c)
{
	memset(a,0,sizeof(a));
	a[0]=strlen(c);
	int i;
	for (i=1;i<=a[0];i++)
	a[i]=c[a[0]-i]-'0';
} 
void cal(int *a,int num)
{
	if (a[0]==1&&a[1]==1) {
	   printf("1\nNumber of hailstone generated:%d",num);
	   return ; 
	} 
	else {
		print(a);	printf(" ");
		ditui(a);
		cal(a,num+1);
	}
}
void ditui(int *a)
{
    int i;
	if (a[1]%2)
	{
		for (i=1;i<=a[0]+1;i++)
		{
		    if (i==1) a[i]=3*a[i]+1;
		    else {
		        a[i]=a[i]*3+a[i-1]/10;
		        a[i-1]%=10;
		    }
		}
		if (a[a[0]+1]) a[0]++;
	}
	else 
	{
	    for (i=a[0];i>=1;i--)
	    {
	    	if (i>1) a[i-1]+=(a[i]%2)*10,a[i]/=2;
	    	else a[i]/=2;
	    }
	    if (a[a[0]]==0) a[0]--;
	}
}
void print(int *a)
{
	int i;
	for (i=a[0];i>=1;i--) printf("%d",a[i]);
}
