# 2.3 数据查询
LOAD DATA INFILE '/var/lib/mysql-files/电影表.txt' INTO TABLE DB_Exp.T_FILM 
 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n'
 IGNORE 1 ROWS;
 
LOAD DATA INFILE '/var/lib/mysql-files/演员表.txt' INTO TABLE DB_Exp.T_ACTOR 
 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n'
 IGNORE 1 ROWS;
 
LOAD DATA INFILE '/var/lib/mysql-files/影院表.txt' INTO TABLE DB_Exp.T_THEATER 
 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n'
 IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/参演表.txt' INTO TABLE DB_Exp.T_ACTIN 
 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n'
 IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/放映表.txt' INTO TABLE DB_Exp.T_SHOW
 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n'
 IGNORE 1 ROWS;
